-- BrightBuy Seed Data
-- Categories: 12 | Products: 43 | Variants: 60

-- ================= CATEGORY =================
INSERT INTO CATEGORY (category_id, name, description, parent_category_id) VALUES ('C01', 'Mobiles', 'Smartphones and feature phones', NULL);
INSERT INTO CATEGORY (category_id, name, description, parent_category_id) VALUES ('C02', 'Laptops', 'Laptops and notebooks', NULL);
INSERT INTO CATEGORY (category_id, name, description, parent_category_id) VALUES ('C03', 'Audio', 'Headphones, earbuds, speakers', NULL);
INSERT INTO CATEGORY (category_id, name, description, parent_category_id) VALUES ('C04', 'Cameras', 'Digital cameras and accessories', NULL);
INSERT INTO CATEGORY (category_id, name, description, parent_category_id) VALUES ('C05', 'Gaming', 'Gaming consoles and accessories', NULL);
INSERT INTO CATEGORY (category_id, name, description, parent_category_id) VALUES ('C06', 'Wearables', 'Smartwatches and fitness bands', NULL);
INSERT INTO CATEGORY (category_id, name, description, parent_category_id) VALUES ('C07', 'SmartHome', 'Smart home and IoT devices', NULL);
INSERT INTO CATEGORY (category_id, name, description, parent_category_id) VALUES ('C08', 'Tablets', 'Tablets and e-readers', NULL);
INSERT INTO CATEGORY (category_id, name, description, parent_category_id) VALUES ('C09', 'ActionFig', 'Action figures and collectibles', NULL);
INSERT INTO CATEGORY (category_id, name, description, parent_category_id) VALUES ('C10', 'BoardGames', 'Board games and puzzles', NULL);
INSERT INTO CATEGORY (category_id, name, description, parent_category_id) VALUES ('C11', 'EduToys', 'Educational and STEM toys', NULL);
INSERT INTO CATEGORY (category_id, name, description, parent_category_id) VALUES ('C12', 'RCVehicles', 'Remote control vehicles', NULL);

-- Total products defined: 43
-- ================= PRODUCT =================
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P001', 'Zynox Phone X1', 'Zynox', 'Flagship smartphone with OLED display', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P002', 'Zynox Phone X1 Lite', 'Zynox', 'Budget smartphone with dual camera', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P003', 'Orbit S9', 'Orbit', 'Mid-range smartphone with fast charging', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P004', 'Orbit S9 Pro', 'Orbit', 'Premium smartphone with triple camera', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P005', 'Vantel Basic', 'Vantel', 'Simple feature phone for calls and texts', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P006', 'Coreline Air 14', 'Coreline', 'Lightweight ultrabook for everyday use', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P007', 'Coreline Pro 15', 'Coreline', 'High-performance laptop for professionals', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P008', 'Nimbus Book 13', 'Nimbus', 'Compact laptop with all-day battery', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P009', 'Nimbus Gamer G5', 'Nimbus', 'Gaming laptop with dedicated GPU', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P010', 'SoundWave Buds Pro', 'SoundWave', 'Noise-cancelling wireless earbuds', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P011', 'SoundWave Buds Lite', 'SoundWave', 'Affordable wireless earbuds', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P012', 'BassCore Headphones', 'BassCore', 'Over-ear headphones with deep bass', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P013', 'BassCore Mini Speaker', 'BassCore', 'Portable Bluetooth speaker', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P014', 'PixelShot D200', 'PixelShot', 'Entry-level DSLR camera', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P015', 'PixelShot Mirror M5', 'PixelShot', 'Compact mirrorless camera', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P016', 'ActionCam GO', 'ActionCam', 'Waterproof action camera', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P017', 'PixelShot Tripod Kit', 'PixelShot', 'Adjustable camera tripod', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P018', 'PlayNext Console X', 'PlayNext', 'Next-gen home gaming console', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P019', 'PlayNext Controller', 'PlayNext', 'Wireless game controller', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P020', 'PlayNext Handheld', 'PlayNext', 'Portable handheld gaming device', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P021', 'GripPro Racing Wheel', 'GripPro', 'Racing wheel with pedals', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P022', 'PulseFit Watch 3', 'PulseFit', 'Smartwatch with heart rate monitor', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P023', 'PulseFit Band Lite', 'PulseFit', 'Basic fitness tracker band', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P024', 'PulseFit Watch Kids', 'PulseFit', 'Smartwatch designed for children', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P025', 'HomeSync Speaker', 'HomeSync', 'Smart speaker with voice assistant', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P026', 'HomeSync Plug', 'HomeSync', 'Wi-Fi smart plug', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P027', 'HomeSync Cam', 'HomeSync', 'Indoor security camera', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P028', 'SlatePad 10', 'SlatePad', '10-inch tablet for browsing and media', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P029', 'SlatePad Mini', 'SlatePad', 'Compact 8-inch tablet', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P030', 'SlatePad Kids', 'SlatePad', 'Durable tablet designed for children', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P031', 'HeroForge Warrior', 'HeroForge', 'Poseable action figure, 6 inch', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P032', 'HeroForge Dragon Beast', 'HeroForge', 'Collectible dragon figure', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P033', 'GalaxyToys Star Fighter', 'GalaxyToys', 'Spaceship collectible model', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P034', 'GalaxyToys Robot Set', 'GalaxyToys', 'Transforming robot figure set', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P035', 'BrainBox Strategy', 'BrainBox', 'Classic strategy board game', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P036', 'BrainBox Family Fun', 'BrainBox', 'Family board game for all ages', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P037', 'PuzzleWorks 1000pc', 'PuzzleWorks', '1000-piece jigsaw puzzle', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P038', 'SmartBuild Blocks', 'SmartBuild', 'STEM building block set', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P039', 'SmartBuild Circuit Kit', 'SmartBuild', 'Beginner electronics learning kit', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P040', 'LearnLab Microscope', 'LearnLab', 'Kids'' science microscope kit', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P041', 'TurboRC Racer', 'TurboRC', 'High-speed remote control car', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P042', 'TurboRC Monster Truck', 'TurboRC', 'Off-road remote control truck', TRUE, NOW());
INSERT INTO PRODUCT (product_id, product_name, brand, description, active, created_at) VALUES ('P043', 'SkyDrone Mini', 'SkyDrone', 'Beginner-friendly mini drone', TRUE, NOW());

-- ================= PRODUCT_CATEGORY =================
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P001', 'C01');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P002', 'C01');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P003', 'C01');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P004', 'C01');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P005', 'C01');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P006', 'C02');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P007', 'C02');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P008', 'C02');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P009', 'C02');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P010', 'C03');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P011', 'C03');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P012', 'C03');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P013', 'C03');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P014', 'C04');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P015', 'C04');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P016', 'C04');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P017', 'C04');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P018', 'C05');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P019', 'C05');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P020', 'C05');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P021', 'C05');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P022', 'C06');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P023', 'C06');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P024', 'C06');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P025', 'C07');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P026', 'C07');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P027', 'C07');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P028', 'C08');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P029', 'C08');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P030', 'C08');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P031', 'C09');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P032', 'C09');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P033', 'C09');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P034', 'C09');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P035', 'C10');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P036', 'C10');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P037', 'C10');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P038', 'C11');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P039', 'C11');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P040', 'C11');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P041', 'C12');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P042', 'C12');
INSERT INTO PRODUCT_CATEGORY (product_id, category_id) VALUES ('P043', 'C12');

-- ================= PRODUCT_VARIANT =================
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V001', 'P001', 'SKU-P001-01', 299.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V002', 'P001', 'SKU-P001-02', 349.99, FALSE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V003', 'P001', 'SKU-P001-03', 349.99, FALSE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V004', 'P002', 'SKU-P002-01', 179.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V005', 'P002', 'SKU-P002-02', 199.99, FALSE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V006', 'P003', 'SKU-P003-01', 279.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V007', 'P004', 'SKU-P004-01', 459.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V008', 'P004', 'SKU-P004-02', 459.99, FALSE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V009', 'P005', 'SKU-P005-01', 39.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V010', 'P006', 'SKU-P006-01', 599.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V011', 'P006', 'SKU-P006-02', 749.99, FALSE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V012', 'P007', 'SKU-P007-01', 999.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V013', 'P007', 'SKU-P007-02', 1299.99, FALSE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V014', 'P008', 'SKU-P008-01', 549.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V015', 'P009', 'SKU-P009-01', 1199.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V016', 'P010', 'SKU-P010-01', 89.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V017', 'P010', 'SKU-P010-02', 89.99, FALSE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V018', 'P011', 'SKU-P011-01', 39.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V019', 'P012', 'SKU-P012-01', 69.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V020', 'P012', 'SKU-P012-02', 69.99, FALSE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V021', 'P013', 'SKU-P013-01', 49.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V022', 'P014', 'SKU-P014-01', 449.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V023', 'P014', 'SKU-P014-02', 549.99, FALSE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V024', 'P015', 'SKU-P015-01', 699.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V025', 'P016', 'SKU-P016-01', 149.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V026', 'P016', 'SKU-P016-02', 199.99, FALSE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V027', 'P017', 'SKU-P017-01', 29.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V028', 'P018', 'SKU-P018-01', 399.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V029', 'P018', 'SKU-P018-02', 449.99, FALSE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V030', 'P019', 'SKU-P019-01', 49.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V031', 'P019', 'SKU-P019-02', 49.99, FALSE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V032', 'P020', 'SKU-P020-01', 199.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V033', 'P021', 'SKU-P021-01', 129.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V034', 'P022', 'SKU-P022-01', 129.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V035', 'P022', 'SKU-P022-02', 139.99, FALSE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V036', 'P023', 'SKU-P023-01', 39.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V037', 'P024', 'SKU-P024-01', 59.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V038', 'P024', 'SKU-P024-02', 59.99, FALSE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V039', 'P025', 'SKU-P025-01', 79.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V040', 'P026', 'SKU-P026-01', 14.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V041', 'P026', 'SKU-P026-02', 24.99, FALSE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V042', 'P027', 'SKU-P027-01', 59.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V043', 'P028', 'SKU-P028-01', 249.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V044', 'P028', 'SKU-P028-02', 299.99, FALSE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V045', 'P029', 'SKU-P029-01', 199.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V046', 'P030', 'SKU-P030-01', 129.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V047', 'P031', 'SKU-P031-01', 19.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V048', 'P032', 'SKU-P032-01', 29.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V049', 'P033', 'SKU-P033-01', 24.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V050', 'P034', 'SKU-P034-01', 34.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V051', 'P035', 'SKU-P035-01', 24.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V052', 'P036', 'SKU-P036-01', 19.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V053', 'P037', 'SKU-P037-01', 14.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V054', 'P038', 'SKU-P038-01', 39.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V055', 'P039', 'SKU-P039-01', 44.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V056', 'P040', 'SKU-P040-01', 29.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V057', 'P041', 'SKU-P041-01', 49.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V058', 'P041', 'SKU-P041-02', 49.99, FALSE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V059', 'P042', 'SKU-P042-01', 59.99, TRUE, TRUE);
INSERT INTO PRODUCT_VARIANT (variant_id, product_id, sku, price, is_default, active) VALUES ('V060', 'P043', 'SKU-P043-01', 69.99, TRUE, TRUE);
-- Total variants inserted: 60

-- ================= PRODUCT_ATTRIBUTES =================
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V001', 'storage', '64GB');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V001', 'color', 'Black');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V002', 'storage', '128GB');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V002', 'color', 'Black');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V003', 'storage', '128GB');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V003', 'color', 'Silver');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V004', 'storage', '32GB');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V004', 'color', 'Blue');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V005', 'storage', '64GB');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V005', 'color', 'Blue');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V006', 'storage', '128GB');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V006', 'color', 'Gray');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V007', 'storage', '256GB');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V007', 'color', 'Black');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V008', 'storage', '256GB');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V008', 'color', 'Gold');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V010', 'ram', '8GB');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V010', 'storage', '256GB SSD');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V011', 'ram', '16GB');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V011', 'storage', '512GB SSD');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V012', 'ram', '16GB');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V012', 'storage', '512GB SSD');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V013', 'ram', '32GB');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V013', 'storage', '1TB SSD');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V014', 'ram', '8GB');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V014', 'storage', '256GB SSD');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V015', 'ram', '16GB');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V015', 'storage', '1TB SSD');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V016', 'color', 'Black');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V017', 'color', 'White');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V019', 'color', 'Black');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V020', 'color', 'Red');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V022', 'kit', 'Body Only');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V023', 'kit', 'With Lens');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V025', 'edition', 'Standard');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V026', 'edition', 'Bundle');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V028', 'storage', '500GB');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V029', 'storage', '1TB');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V030', 'color', 'Black');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V031', 'color', 'Blue');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V034', 'color', 'Black');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V035', 'color', 'Rose Gold');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V037', 'color', 'Blue');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V038', 'color', 'Pink');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V040', 'pack', 'Single');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V041', 'pack', '2-Pack');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V043', 'storage', '64GB');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V044', 'storage', '128GB');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V057', 'color', 'Red');
INSERT INTO PRODUCT_ATTRIBUTES (variant_id, attribute_name, attribute_value) VALUES ('V058', 'color', 'Green');
-- Total attribute rows inserted: 50